### PR TITLE
Fixes to packages, Added group project, Fix to CtrlDemo compilation etc.

### PR DESCRIPTION
**Pull request by birbilis**
- fixed the Packages of Image32 (were trying to pull in older files that had been renamed/reorginanized [like the Img32.SVG.Writter instead of Img32.Storage and Clipper instead of Clipper2 etc.])
- fixed CtrlDemo compilation (had to copy Img32.Storage and Img32.Layers to it and add a modified .inc file in that demo's folder to allow TStorageManager to be pulled in / compiled - could have used hard links for those two libs [so that they're maintained in one place [in /source] but even though the concept of such links exists in Unixes and GitHub now supports them, such links are only supported on Windows in NTFS, not FAT32, so opted to not try that, plus older Git clients may not support them)
- added group project so that one (at least in D11.1) can right click on the root of it and to a Build All to get build of the packages (had to add .dproj files for those too, to then add to groupproj) and of the example projects easily and then try the demos they want easily by double-clicking on each project under the group project to activate it and then run (to install the design package if needed obviously you right click and install it). Also added explicit dependencies in that group project for the demos to build the Img32_Package first (obviously when you do build all it builds from top to bottom if there are no dependencies set and I have placed the package projects first in the groupproj)

----

note that to install the build/install the design package in Delphi you need to not have SVGIconImageList package installed in GetIt (it seems to install its own package for Image32)

### CODE REVIEW

**Comment by birbilis** [comment]
newer commit:
- making DPIAware functions available for all platforms (all those functions just use DpiAwareOne and Img32.FMX.pas adjusts it via ScreenService.GetScreenScale)

**Comment by birbilis** [comment]
- updated Target Platforms for the various projects and packages
- added FMX and VCL specific versions of the Imag32 library package (that add the rest of the FMX and VCL specific units and pull-in dependency to FMX and VCL framework respectively)

**Comment by birbilis** [comment]
please do check if the demo projects still build fine with Lazarus etc. (only trying with Delphi 11.1)

**Comment by birbilis** [comment]
New commit:
- Fix for blueish tint (R-B channel swap) on OS-X

**Comment by birbilis** [comment]
New commit:
* Fix for blueish tint for Android

**Comment by AngusJohnson** [comment]
I'm closing this PR because I couldn't duplicate the color problems that George has reported. 
And without others reporting similar issues I'm not sure just how widespread this issue is (and how much time/effort I need to devote to solving it).

**Pull request closed without merging**
