### PR TITLE
Improve Rasterization performance

### PR DESCRIPTION
**Pull request by ahausladen**
This PR improves the performance of the Rasterize function by helping the compiler to use CPU registers instead of stack variables and by skipping floating point operations that result in the same value as the previous iteration.

**Changes**
- Better CPU register allocation
- Reduction of dynamic array allocations by reusing the existing dynarray.
- Fixed calculation error in TBarycentricRenderer.RenderProc: "255*255 shr 8=254" must be "Round(255*255/255)=255"
- Moved FillRule code into dedicated CPU register optimized "FillByteBufferXxx" functions (one per FillRule, more similar code but much faster)
- Fast forward "windingAccum[idx] = 0" values with FillChar
- Removed: FillChar(byteBuffer), FillByteBuffer does the zero-ing
- Removed: FillChar(windingAccum), FillByteBuffer resets windingAccum
- Removed a float multiplication in ProcessScanlineFragments
- Moved the "unary minus" to the constant multiplier in FillByteBufferNegative: "-accum*318" -> "accum*-318", removing a float subtraction
- Replace "array[] of 4*Double" with "array[] of PFragment". Better readable code and slightly faster due to not incrementing the "frags" pointer for every element.
- Change DynArray parameter modifiers from "var" to "const", what removes indirect memory accesses. ("const" makes the variable "const", not the contents and removes reference counting)
- Change Rasterize's byteBuffer from DynArray to GetMem/FreeMem, it doesn't need to be initialized with zeros.
- TColorRenderer.RenderProc optimization:
   Added an optimized function that only calls BlendToAlpha if the pixel is not identical to the previous or the alpha channel has changed. A special "super fast" mode for alpha=255 is also added.

### CODE REVIEW

**Comment by AngusJohnson** [comment]
Excellent! 
I'd drawn a blank on how to improve performance, so I'm especially delighted that you've managed to do that.
It'll take me a while to process what you've done, which I want to do before I merge.

Also, I've barely had a look so far but shouldn't the `colors` parameter in your `ReverseColors` procedure be passed a `var` not `const`?

**Comment by ahausladen** [comment]
You can take your time to "process" the changes and accept or decline them. They are a lot and due to Delphi's inability to optimize the code properly (saying C++, C# and Java do a lot better in that department, would be an understatement), it means that the code becomes less readable. That's the reason why I left the original TColorRenderer.RenderProc code as a comment. The original code is much more readable than the optimized one.

Especially CPU register optimizations in Delphi means that the code will be bloated but in the end it runs faster. Delphi's Win32 and Win64 code optimizer haven't really changed since Delphi 6 (Win32) and XE2 (Win64 introduction). Especially Win64 is really bad and doesn't even know all the tricks the Win32 compiler has and for some unknown reason really likes to use the XMM6 register that must be backup-ed before using it, whereas XMM3 and XMM4 are free and don't need to be backup-ed.

### "var" vs. "const" (1)
I had the ```var``` before I changed it to ```const```. Delphi doesn't know C++'s const-ness. So the ```const``` in Delphi only makes the variable const (like "final" in Java). The content isn't affected by ```const```.

The ReverseColors parameter is a dynamic array, which itself is already a pointer to the first element. Using ```var``` means that we get "a pointer to a pointer to the first element". So if the code accesses an array element, it has to deference twice. ReverseColors doesn't call SetLength or assigns a new array to the parameter variable. It only changes its elements. And that's why ```const``` works here and we only get the "pointer to the first element".

An "I don't want the reference counting" modifier would be nice, because with the ```const```, one instinctively thinks that you can't change it including the content. But ```const``` doesn't mean that. The alternative would be to pass ```@colors[0]``` and ```Length(colors)```, making it really obvious that you want to change the content only. ReverseColors is an internal function, so  that would a possibility.


### MakeColorGradient (2)
Yes, the dynamic array ```Result``` is passed as last parameter. But for managed data types (string, dynarray, interface, records with managed datatypes) Delphi introduces a temporary helper variable on the caller's side and passes this to the function, so that the variable in the caller isn't modified while the MakeColorGradient is running. After the function call returns, the ```_DynArrayAsg``` function is called to assign the temporary helper variable to the actual variable. And _DynArrayAsg does at least two CPU LOCKs and in case the actual variable wasn't NIL (what it isn't in our case), the old dynamic array's reference counter is decremented and becomes zero resulting in a FreeMem call.
By using the explicit ```var``` parameter for the array, the temporary helper variable is omitted.

It is Delphi's ABI (Application Binary Interface) that forces this behavior. The "Result" variable on the caller's side must not change until the function returns.
For example, if you would return an "Integer", the result is only assigned to the caller's variable after the function returned. In the function you can change ```Result``` without affecting the caller's variable at all. The function puts its return value into the "EAX" CPU register and the caller then copies "EAX" to the actual variable.
In order to uphold this behavior, the compiler needs the temporary helper variable that can be freely modified by the function and after the return, it assigns it to the actual variable. (Not speaking of Delphi ignoring that ABI if you have an unmanaged record who's SizeOf isn't 1, 2, 4 and 8).

### OVERFLOWCHECKS_ENABLED (3)
Well, there is one pull request incoming. But the code isn't finished yet and there are multiple ways to make parsing SVG files in Img32.Core.pas faster. One doesn't change "that much" and is less work to to, but will be slightly slower and one that changes the code a lot. I haven't decided yet, what way is the right way to go and there is a lot of optimization potential in Img32.Core.pas without having to spend hours in CPU register optimizations (as much fun that is, but it should really be the compiler's job).

It will be used to fix the leaking ```{$OVERFLOWCHECKS ON}``` in the Img32.Core.pas. After that compiler directive, overflow checks are "on" for all the function below, making them slower as they could be.

**Comment by tomwiel** [comment]
My comment is bit offtopic, but is also about optimization:

IMHO (but I maybe mistaken) TDrawData is wanted like a kind of extensible record.
SVG specifies a lot of attributes, but adding more (mostly unused) record fields is bad (?) for parameter size.
The number of declared attributes per element (in svg file) is low, so maybe add a (mostly short) flexible array?
```
TDrawData = record ...; ... moreAttribs: TddAttribs; end;
TddAttribs = array of TddAttrib;
TddAttrib = record 
  nameHash: cardinal; // attr name
  typ: TddAttribType;  // value type
  case byte of
  0: (iValue: integer); 
  1: (fValue: single); 
  2: (sValue: cardinal); // string hash (for SVG string constants)
end;
```

**Comment by ahausladen** [comment]
> IMHO (but I maybe mistaken) TDrawData is wanted like a kind of extensible record.

That record is also on my todo list, but mostly because of the many UTF8Strings and the dyn-array in it. Those make it a managed record, what requires _CopyRecord and _FinalizeRecord calls in the function prolog and epilog, which uses the slow RTTI to copy and clear the fields.


> 
> ```Delphi
> TDrawData = record ...; ... moreAttribs: TddAttribs; end;
> TddAttribs = array of TddAttrib;
> TddAttrib = record 
>   nameHash: cardinal; // attr name
>   typ: TddAttribType;  // value type
>   case byte of
>   0: (iValue: integer); 
>   1: (fValue: single); 
>   2: (sValue: cardinal); // string hash (for SVG string constants)
> end;
> ```
Accessing the properties via name is definitely faster than searching an attribute list.

The main problem I see with the current record type is, that the SVG elements modify it and then pass it to their children, but that can't be changed as it is the nature of CSS. That's why the drawDat parameters must be copies of their caller's version and can't be made "const". With your suggested record type the merge will need search-loops for the properties and dyn-array resizing, what could be slow.

The questing is, is it faster than the current managed record handling? And that depends on the number of accumulated properties that are defined down the SVG tree structure. At the moment the UpdateDrawInfo function has to check every property, but with the suggested record type it would only have to "find" one or two properties. But what about merging in the fDrawDat of the SVG element itself. Every Draw() method has 3 TDrawDat. The one from the parent, the element's one and then the merged one. At the moment the parent's TDrawDat is a copy (no "const" parameter) and is used as merge target.

---

How would it be to have something like the following, that allows "merging" without merging. It uses overlaying instead. The Draw() methods would have to "cache" the values in local variables if they are used multiple times, but that would also be necessary for your suggested record type.

```Delphi
type
  PDrawData = ^TDrawData;
  TDrawData = record
    ParentDrawData: PDrawData; // a fallback if Attributes and ElementDrawData don't have the nameHash attribute
    ElementDrawData: PDrawData; // a fallback if Attributes doesn't have the nameHash attribute 
    Attributes: TddAtrribs;

    function GetAttr(nameHash: cardinal): PddAttrib;
    function GetStringAttr(nameHash: cardinal): UTF8String;
    function GetIntAttr(nameHash: cardinal): integer;
    // ...
  end;

function TDrawData.GetAttr(nameHash: cardinal): PddAttrib;
var
  i: integer;
begin
  i := IndexOf(nameHash);
  if i >= 0 then
    Result := @Attributes[i];
  else
  begin
    Result := nil;
    if ElementDrawData <> nil then
      Result := ElementDrawData.GetAttr(nameHash);
    if (Result = nil) and (ParentDrawData <> nil) then
      Result := ParentDrawData.GetAttr(nameHash);
end;

function TDrawData.GetIntAttr(nameHash: cardinal): integer;
var
  item: PddAttrib;
begin
  item := GetAttr(nameHash);
  Result  := 0;
  if item <> nil then
    Result := item.iValue;
end;
```
That way only 3 fields have to be copied on the stack (still one being a dynarray => _CopyRecord) but the whole merge duplication and dynarray resizing is gone.

The Draw methods must then initialize their new "merge" TDrawData.
```Delphi
procedure TGroupElement.Draw(image: TImage32; const parentDrawDat: TDrawData);
var
  drawDat: TDrawDat;
begin
  UpdateDrawInfo(drawDat, parentDrawDat, Self);

  if drawDat.getIntAttr(hFill_045_Rule) Ord(frNegative) then
    drawDat.setIntAttr(hFill_045_Rule, Ord(frNonZero));
  // ...
end;

procedure UpdateDrawInfo(var drawDat: TDrawDat; const parentDrawDat: TDrawDat; element: TSVGElement);
begin
  drawDat.ParentDrawDat := parentDrawDat;
  drawDat.ElementDrawDat := element.fDrawDat; // element.fDrawDat.Parent/ElementDrawDat is always NIL
  drawDat.Attributes := nil; // used if SetXxxAttr() is called

  //... Copy explicitly defined fields?
end;
```
Here we have a three layers model. The Parent-DrawDat, the Element-DrawDat and the "Modified"-DrawDat. So GetIntAttr() has to look into all three of them (in reverse order) and SetIntAttr() only modifies and resizes the "Modified"-DrawDat's "Attributes" dynarray.

But those are only the CSS styles. There are also TMatrixD and TRectD and useEl: TBaseElement fields in the TDrawData record, that wouldn't fit into the Attributes dynarray. Fortunately they aren't managed data types, so copying them isn't that expensive, but there is no marker that tells, if the ParentDrawData, the Element-DrawData or the "Modified"-DrawData contains their actual value.

---

BTW: A simple optimization to reduces the managed record handling in the current code base would be to change TBaseElement.DrawChildren()'s drawDat parameter to "const" and because nothing overrides the method, the "virtual" could also be dropped from it. But that leaves all the other Draw() methods, so not much saved unless the SVG has a deep tree.

**Comment by tomwiel** [comment]
Yes, this layers model looks more optimal.
I also vote that UpdateDrawInfo() initially copies all predefined fields (from ParentDrawDat to drawDat), 
so they would be the same as in previous library versions. The goal to limit the parameter-record size looks solved now:)

**Comment by AngusJohnson** [comment]
> You can take your time to "process" the changes and accept or decline them. They are a lot and due to Delphi's inability to optimize the code properly (saying C++, C# and Java do a lot better in that department, would be an understatement), it means that the code becomes less readable. 

In this specific instance, minor performance gains are valuable, though generally I prefer readable over minor performance improvements. The sort of software I've been writing _as a hobby_ for >50yrs hasn't been performance critical until recently. So I'm limited in experience/ability WRT under-the-hood optimisations and have relied on the compiler to do a decent job there. And sadly Delphi really can't compete with the languages you've mentioned since Borland ... Embercadero never had the user base to justify the R&D expense to optimise code really well.

**`var vs const`**

> The alternative would be to pass @colors[0] and Length(colors), making it really obvious that you want to change the content only. 

But ugly 😜. 
Given your explanation, my preference would be to include a comment indicating that the parameter is intentionally passed as a `const` as a performance optimisation.

**`MakeColorGradient`**

Thank you for your very detailed explanation, which I've only partially followed 😱. 
Nevertheless I get the gist that passing a `var` parameter to a procedure may be more efficient than using functions returning managed types. 

**`OVERFLOWCHECKS_ENABLED`**

> Well, there is one pull request incoming.

👍🤞🤣.


**`TDrawData`**

Thank you both (Tom & Andreas) for your very helpful suggestions. 
A PR would indeed be well received, but otherwise I'm pretty occupied with another project.

**Comment by ahausladen** [comment]
**`MakeColorGradient`**
Code can express that better than words:

```Delphi
var
  A: TColor32Array;
begin
  A := MakeColorGradient();
end;
```
is transformed into this by the compiler

```Delphi
var
  A, tmpHelper: TColor32Array;
begin
  Pointer(tmpHelper) := nil;
  Pointer(Arr) := nil;
  try

    MakeColorGradient({var} tmpHelper);
    _DynArrayAsg(_A, tmpHelper); // Delphi upholds the rule that "A" must not change before MakeColorGradient returns

  finally
    _DynArrayClear(tmpHelper);
    _DynArrayClear(A);
  end;
end;
```

whereas 

```Delphi
var
  A: TColor32Array;
begin
  MakeColorGradient({var} A);
end;
```
becomes
```Delphi
var
  A: TColor32Array;
begin
  Pointer(A) := nil;
  try
    MakeColorGradient({var} A);
  finally
    _DynArrayClear(A);
  end;
end;
```

**Pull request merged**
